---
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit #optiona
    environment:
      - ALLOW_INSECURE_HTTP=true
    volumes:
      - ./kasm/data:/opt
      - ./kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 9033:3000
      - 9034:443
    restart: unless-stopped


#  kasm:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   ports:
#     - "8080:443"
#   volumes:
#     - ./kasm:/config
#   environment:
#     - ADMIN_PASS=amazonawS3a7abb
#     - ALLOW_INSECURE_HTTP=true
#   restart: always
#   privileged: true
